# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${log_dir}

job_logging:
  handlers:
    file:
      filename: ${log_dir}/${hydra.job.name}.log
